[packages]
neovim = {
  github = "neovim/neovim",
  asset_pattern = "nvim-linux-x86_64.appimage",
  version = "stable",
  binaries = [
    { source = "neovim", link_as = "nvim" }
  ]
}
ripgrep = {
  github = "BurntSushi/ripgrep",
  asset_pattern = "ripgrep-*-x86_64-unknown-linux-musl.tar.gz",
  version = "*"
}
tmux = {
  github = "tmux/tmux-builds",
  asset_pattern = "tmux-*-linux-x86_64.tar.gz",
  version = "*"
}
lazygit = {
  github = "jesseduffield/lazygit",
  asset_pattern = "lazygit_*_linux_x86_64.tar.gz",
  version = "*"
}
fd = {
  github = "sharkdp/fd",
  asset_pattern = "fd-v*-x86_64-unknown-linux-musl.tar.gz",
  version = "*"
}
zoxide = {
  github = "ajeetdsouza/zoxide",
  asset_pattern = "zoxide-*-x86_64-unknown-linux-musl.tar.gz",
  version = "*",
}
bat = {
  github = "sharkdp/bat",
  asset_pattern = "bat-v*-x86_64-unknown-linux-musl.tar.gz",
  version = "*",
}
eza = {
  github = "eza-community/eza",
  asset_pattern = "eza_x86_64-unknown-linux-musl.tar.gz",
  version = "*",
}
tree-sitter-cli = {
  github = "tree-sitter/tree-sitter",
  asset_pattern = "tree-sitter-cli-linux-x86.zip",
  version = "*",
}
