# Execute your favorite apps at launch
exec-once = wl-paste --type text --watch cliphist store # clipboard
exec-once = wl-paste --type image --watch cliphist store
exec-once = hypridle
exec-once = $TERMINAL
exec-once = nm-applet & # for network configurations
exec-once = flatpak run com.bitwarden.desktop # for the SSH agent
exec-once = flatpak run com.todoist.Todoist # for my todo list
exec-once = flatpak run eu.betterbird.Betterbird # for mails and notifications
exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP SSH_AUTH_SOCK
exec-once=qs -c "noctalia-shell"
exec-once=systemctl start --now hyprpolkitagent
