[font]
size = 12.0

[font.normal]
family = "Fira Mono"
style = "Medium"

[window.padding]
x = 6
y = 6

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"
